### ISSUE TITLE
Bot running successfully but not forwarding

### ISSUE THREAD

**Issue by shad0w-cat** [MrMissx/Telegram_Forwarder#38]
The bot is running successfully but it ain't forwarding anything. No files no messages. There is no error in Heroku log. Does it work for new files/messages only?
(Already verified ids multiple times and also used - sign)

**Comment by keselekpermen69** [comment]
Hi, does the bot was a member of both chat (FROM_CHATS and TO_CHATS)? The bot can't get any update if the bot wasn't on the chats.
If thats not the case, provide me more detailed info like FROM_CHATS and TO_CHATS config since i can't reproduce any kind of this behaviour if not .
It should work by all incoming message in the FROM_CHATS (incuding media, document, voice, etc).

**Comment by shad0w-cat** [comment]
No, the bot is only the member of one chat to which it will forward to. But I have tried using both the ids of channel in which bot is present still nothing! The bot only replies to me for the following commands /start, /help and /id and that too in personal message not in any of the channel. Both channels are private. Though
